name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Determine event type
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Running CI for a Pull Request to ${{ github.base_ref }}"
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "Running CI for a Merge to ${{ github.ref_name }}"
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Trigger CD on merge
        if: github.event_name == 'push'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: trigger-cd
          client-payload: '{"ref": "${{ github.ref }}", "branch": "${{ github.ref_name }}"}'